# The below pipeline is designed to build the .jar for petclinic app and then deploy it from an Ansible control node
# https://aka.ms/yaml


trigger:
- main

pool:
  name: Default

stages:
  - stage: Test
    jobs:
    - job: QodanaLint
      steps:
       - checkout: self

       - script: mkdir -p $(System.DefaultWorkingDirectory)/qodana/results
         displayName: 'Create results path'

       - script: |
           set -e
           docker run --rm \
           -v $(System.DefaultWorkingDirectory):/data/project \
           -v $(System.DefaultWorkingDirectory)/qodana/results:/data/results \
           jetbrains/qodana-jvm
         displayName: 'Run linter'

       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: '$(System.DefaultWorkingDirectory)/qodana/results'
           ArtifactName: 'qodana-report'
           publishLocation: 'Container'

  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - task: Maven@4
        inputs:
          #azureSubscription: 'Azure subscription 1(0fa225b2-6ae6-47ee-931c-b34ef669c09c)'
          mavenPomFile: 'pom.xml'
          goals: 'package'

      - publish: 'target/spring-petclinic-3.5.0-SNAPSHOT.jar'
        artifact: 'drop'

  - stage: Deploy
    dependsOn: Build 
    jobs:
    - job: DeployJob
      steps:
       - download: current
         artifact: drop
       - script: ansible-playbook -i /home/osansible/ansibleconfig/inventories/inventory.ini /home/osansible/ansibleconfig/main_playbook.yml
         displayName: 'Deploying app with Ansible'    

