name: Collect PR Reviews for Memory

on:
  pull_request_review:
    types: [submitted]
  # Also trigger on review comments (inline comments)
  pull_request_review_comment:
    types: [created]

jobs:
  collect-review:
    runs-on: ubuntu-latest
    # Only run for actual reviews, not just comments
    if: github.event.review.state != 'commented' || github.event.action == 'created'
    
    permissions:
      contents: write
      pull-requests: read
      
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure Git Identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Checkout memory branch
      run: |
        # Create memory branch if it doesn't exist
        git fetch origin memory:memory 2>/dev/null || git checkout --orphan memory
        git checkout memory 2>/dev/null || {
          git checkout --orphan memory
          git rm -rf . 2>/dev/null || true
          mkdir -p memory_data
          echo '{"embeddings": [], "metadata": {"version": "1.0", "created": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}}' > memory_data/metadata.json
          git add memory_data/metadata.json
          git commit -m "Initialize memory branch" --allow-empty
          git push origin memory
        }
        
    - name: Extract and process review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO_NAME: ${{ github.repository }}
        REVIEW_ID: ${{ github.event.review.id || github.event.comment.id }}
        EVENT_TYPE: ${{ github.event_name }}
      run: |
        python scripts/extract_review.py
        
    - name: Update memory and push
      run: |
        # Add all changes in memory_data directory
        git add memory_data/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update memory: PR #${{ github.event.pull_request.number }} review by @${{ github.event.review.user.login || github.event.comment.user.login }}"
          git push origin memory
          echo "✅ Memory updated successfully"
        fi